// GENERATED by scripts/extract-data.mjs from the legacy index.html — do not edit by hand.
// Re-run `npm run extract` (against the pre-conversion index.html) to regenerate.

export interface StatCard { label: string; value: string; }
export interface SessionStep { time: string; desc: string; }

/** An exercise as it appears in a specific workout (sets/reps and dumbbell count are per-workout). */
export interface WorkoutExercise {
  slug: string;
  /** Display name as shown in the workout card (can differ from EXERCISE_DATA name). */
  name: string;
  setsReps: string;
  /** Number of dumbbells used; 0 = bodyweight. */
  dumbbells: number;
}

export interface Workout {
  id: string;
  badge: string;
  name: string;
  exercises: WorkoutExercise[];
}

/** Core-finisher card. Free text — names are NOT EXERCISE_DATA slugs. */
export interface CoreItem { name: string; desc: string; setsReps: string; }

export interface Phase {
  index: number;
  tabName: string;
  monthsLabel: string;
  title: string;
  goal: string;
  stats: StatCard[];
  sessionStructure: SessionStep[];
  workoutsLabel: string;
  rotationNote: string;
  workouts: Workout[];
  coreLabel: string;
  core: CoreItem[];
}

export const PHASES: Phase[] = [
  {
    "index": 0,
    "tabName": "Foundation",
    "monthsLabel": "Months 1–3",
    "title": "Foundation",
    "goal": "Learn the movements and build the habit. Each session is 7 exercises × 3 sets — light enough to focus on form but enough volume to start adapting. Lower body and back take a beating; upper body stays controlled and conservative.",
    "stats": [
      {
        "label": "Session length",
        "value": "40–45 min"
      },
      {
        "label": "Rest between sets",
        "value": "90 sec"
      },
      {
        "label": "Rest between exercises",
        "value": "90 sec"
      },
      {
        "label": "Tempo",
        "value": "Slow & controlled"
      },
      {
        "label": "Workouts / week",
        "value": "3"
      }
    ],
    "sessionStructure": [
      {
        "time": "5 min",
        "desc": "Warm-up — arm circles, hip circles, bodyweight squats, jumping jacks"
      },
      {
        "time": "30–35 min",
        "desc": "Main workout — 7 exercises, 2 sets each"
      },
      {
        "time": "5 min",
        "desc": "Cool-down — hold each stretch 20–30 sec"
      }
    ],
    "workoutsLabel": "Workouts — alternate A → B → A each week, then B → A → B the next",
    "rotationNote": "Rotation: Week 1: A–B–A · Week 2: B–A–B · repeat",
    "workouts": [
      {
        "id": "p1-a",
        "badge": "Workout A",
        "name": "Full body — push focus",
        "exercises": [
          {
            "slug": "goblet-squat",
            "name": "Goblet squat",
            "setsReps": "3 × 10",
            "dumbbells": 1
          },
          {
            "slug": "db-romanian-deadlift",
            "name": "DB Romanian deadlift",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-floor-press",
            "name": "DB floor press",
            "setsReps": "3 × 8",
            "dumbbells": 2
          },
          {
            "slug": "db-bent-over-row",
            "name": "DB bent-over row",
            "setsReps": "3 × 8",
            "dumbbells": 2
          },
          {
            "slug": "db-lateral-raise",
            "name": "DB lateral raise",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-curl",
            "name": "DB curl",
            "setsReps": "3 × 8",
            "dumbbells": 2
          },
          {
            "slug": "db-tricep-overhead-extension",
            "name": "DB tricep overhead extension",
            "setsReps": "3 × 8",
            "dumbbells": 1
          }
        ]
      },
      {
        "id": "p1-b",
        "badge": "Workout B",
        "name": "Full body — pull focus",
        "exercises": [
          {
            "slug": "goblet-squat",
            "name": "Goblet squat",
            "setsReps": "3 × 10",
            "dumbbells": 1
          },
          {
            "slug": "db-romanian-deadlift",
            "name": "DB Romanian deadlift",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-overhead-press",
            "name": "DB overhead press",
            "setsReps": "3 × 8",
            "dumbbells": 2
          },
          {
            "slug": "db-front-raise",
            "name": "DB front raise",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-shrug",
            "name": "DB shrug",
            "setsReps": "3 × 12",
            "dumbbells": 2
          },
          {
            "slug": "hammer-curl",
            "name": "Hammer curl",
            "setsReps": "3 × 8",
            "dumbbells": 2
          },
          {
            "slug": "db-bent-over-row",
            "name": "DB bent-over row",
            "setsReps": "3 × 8",
            "dumbbells": 2
          }
        ]
      }
    ],
    "coreLabel": "Core — add 3 of these at the end of each session, rotate through them",
    "core": [
      {
        "name": "Dead bug",
        "desc": "Lie on back, arms up, knees at 90°. Lower opposite arm and leg slowly, return.",
        "setsReps": "3 × 8 each side"
      },
      {
        "name": "DB crunch",
        "desc": "Lie on back, hold one dumbbell on chest. Crunch shoulders off floor. No neck pulling.",
        "setsReps": "3 × 12"
      },
      {
        "name": "Leg raise",
        "desc": "Lie flat, legs straight, lower back pressed to floor. Raise legs to 90°, lower slowly.",
        "setsReps": "3 × 10"
      },
      {
        "name": "Bird dog",
        "desc": "On all fours, extend opposite arm and leg simultaneously. Hold 2 sec.",
        "setsReps": "3 × 8 each side"
      },
      {
        "name": "Heel tap",
        "desc": "Lie on back, knees bent. Crunch sideways to tap each heel alternately.",
        "setsReps": "3 × 15 each side"
      },
      {
        "name": "Seated knee tuck",
        "desc": "Lean back slightly, hands behind you. Draw both knees to chest, extend out. Lower abs.",
        "setsReps": "3 × 12"
      }
    ]
  },
  {
    "index": 1,
    "tabName": "Building",
    "monthsLabel": "Months 4–6",
    "title": "Building",
    "goal": "The split widens to three workouts (legs+biceps / push / pull) and weights step up meaningfully. Bulgarian split squats enter, plus rear delt fly and face pulls to balance shoulder development. Volume drops slightly per exercise; intensity rises.",
    "stats": [
      {
        "label": "Session length",
        "value": "45–55 min"
      },
      {
        "label": "Rest between sets",
        "value": "90 sec"
      },
      {
        "label": "Rest between exercises",
        "value": "90 sec"
      },
      {
        "label": "Tempo",
        "value": "2 sec down"
      },
      {
        "label": "Workouts / week",
        "value": "3"
      }
    ],
    "sessionStructure": [
      {
        "time": "5 min",
        "desc": "Warm-up — include 1 light set of first exercise at 50% weight"
      },
      {
        "time": "35–45 min",
        "desc": "Main workout — 7 exercises, 2–3 sets each"
      },
      {
        "time": "5 min",
        "desc": "Cool-down — stretch muscles trained that session"
      }
    ],
    "workoutsLabel": "Workouts — 3-way rotation A → B → C → A → B → C",
    "rotationNote": "Rotation: A → B → C · repeating cycle",
    "workouts": [
      {
        "id": "p2-a",
        "badge": "Workout A",
        "name": "Lower + biceps",
        "exercises": [
          {
            "slug": "db-sumo-squat",
            "name": "DB sumo squat",
            "setsReps": "3 × 10–12",
            "dumbbells": 1
          },
          {
            "slug": "db-bulgarian-split-squat",
            "name": "DB Bulgarian split squat ★",
            "setsReps": "3 × 8 each",
            "dumbbells": 2
          },
          {
            "slug": "db-romanian-deadlift",
            "name": "DB Romanian deadlift",
            "setsReps": "3 × 10–12",
            "dumbbells": 2
          },
          {
            "slug": "db-glute-bridge",
            "name": "DB single-leg glute bridge",
            "setsReps": "3 × 12",
            "dumbbells": 1
          },
          {
            "slug": "standing-db-curl",
            "name": "Standing DB curl",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "concentration-curl",
            "name": "Concentration curl",
            "setsReps": "2 × 10",
            "dumbbells": 2
          }
        ]
      },
      {
        "id": "p2-b",
        "badge": "Workout B",
        "name": "Push — chest & shoulders",
        "exercises": [
          {
            "slug": "db-goblet-squat",
            "name": "DB goblet squat",
            "setsReps": "3 × 10",
            "dumbbells": 1
          },
          {
            "slug": "db-glute-bridge",
            "name": "DB single-leg glute bridge",
            "setsReps": "3 × 12",
            "dumbbells": 1
          },
          {
            "slug": "db-floor-press",
            "name": "DB floor press",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-overhead-press",
            "name": "DB overhead press",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-lateral-raise",
            "name": "DB lateral raise",
            "setsReps": "3 × 12",
            "dumbbells": 2
          },
          {
            "slug": "db-rear-delt-fly",
            "name": "DB rear delt fly",
            "setsReps": "2 × 12",
            "dumbbells": 2
          },
          {
            "slug": "tricep-kickback",
            "name": "Tricep kickback",
            "setsReps": "3 × 10",
            "dumbbells": 2
          }
        ]
      },
      {
        "id": "p2-c",
        "badge": "Workout C",
        "name": "Pull — back & biceps",
        "exercises": [
          {
            "slug": "db-sumo-squat",
            "name": "DB sumo squat",
            "setsReps": "3 × 10",
            "dumbbells": 1
          },
          {
            "slug": "db-romanian-deadlift",
            "name": "DB Romanian deadlift",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-bent-over-row",
            "name": "DB bent-over row",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-single-arm-row",
            "name": "DB single-arm row",
            "setsReps": "3 × 10 each",
            "dumbbells": 2
          },
          {
            "slug": "db-face-pull-floor",
            "name": "DB face pull (floor)",
            "setsReps": "3 × 12",
            "dumbbells": 2
          },
          {
            "slug": "db-shrug",
            "name": "DB shrug",
            "setsReps": "3 × 12",
            "dumbbells": 2
          },
          {
            "slug": "hammer-curl",
            "name": "Hammer curl",
            "setsReps": "3 × 10",
            "dumbbells": 2
          }
        ]
      }
    ],
    "coreLabel": "Core — pick 3 per session, rotate. More variety than Phase 1.",
    "core": [
      {
        "name": "DB crunch",
        "desc": "Dumbbell on chest. Controlled crunch, don't use momentum.",
        "setsReps": "3 × 15"
      },
      {
        "name": "DB Russian twist",
        "desc": "Sit at 45°, hold one dumbbell, rotate side to side. Feet on floor. Oblique focus.",
        "setsReps": "3 × 12 each side"
      },
      {
        "name": "Leg raise",
        "desc": "Lower back flat, raise straight legs to 90° and lower slowly.",
        "setsReps": "3 × 12"
      },
      {
        "name": "Seated knee tuck",
        "desc": "Lean back slightly, hands behind you. Draw both knees to chest. Keep feet off floor the whole set.",
        "setsReps": "3 × 15"
      },
      {
        "name": "Dead bug",
        "desc": "Arms up, knees at 90°. Lower opposite arm and leg simultaneously. Lower back stays on floor.",
        "setsReps": "3 × 10 each side"
      },
      {
        "name": "DB woodchop",
        "desc": "Hold one dumbbell with both hands. Rotate and chop diagonally from high to low.",
        "setsReps": "3 × 10 each side"
      }
    ]
  },
  {
    "index": 2,
    "tabName": "Intensity",
    "monthsLabel": "Months 7–9",
    "title": "Intensity",
    "goal": "Heavier straight sets with full 2-minute rests. Same 3-workout split, fewer working sets per exercise but considerably more load. This is where strength gains start showing visibly. Sessions are longer (60–75 min) — that's the trade-off for the heavier work.",
    "stats": [
      {
        "label": "Session length",
        "value": "60–70 min"
      },
      {
        "label": "Rest between sets",
        "value": "2 min"
      },
      {
        "label": "Rest between exercises",
        "value": "2 min"
      },
      {
        "label": "Tempo",
        "value": "2 sec down"
      },
      {
        "label": "Workouts / week",
        "value": "3"
      }
    ],
    "sessionStructure": [
      {
        "time": "5 min",
        "desc": "Warm-up — light movement + 1 warm-up set of first exercise"
      },
      {
        "time": "50–60 min",
        "desc": "Main workout — 7 exercises, 3 straight sets, 2 min rest"
      },
      {
        "time": "5 min",
        "desc": "Cool-down — stretch every major muscle group worked"
      }
    ],
    "workoutsLabel": "Workouts — A → B → C rotation, straight sets",
    "rotationNote": "Rotation: A → B → C · straight sets, heavier weight, 2 min rest between sets",
    "workouts": [
      {
        "id": "p3-a",
        "badge": "Workout A",
        "name": "Lower body — heavy sets",
        "exercises": [
          {
            "slug": "db-goblet-squat",
            "name": "DB goblet squat",
            "setsReps": "3 × 12",
            "dumbbells": 1
          },
          {
            "slug": "db-romanian-deadlift",
            "name": "DB Romanian deadlift",
            "setsReps": "3 × 12",
            "dumbbells": 2
          },
          {
            "slug": "db-bulgarian-split-squat",
            "name": "DB Bulgarian split squat",
            "setsReps": "3 × 10 each",
            "dumbbells": 2
          },
          {
            "slug": "db-glute-bridge",
            "name": "DB single-leg glute bridge",
            "setsReps": "3 × 15",
            "dumbbells": 1
          },
          {
            "slug": "db-calf-raise",
            "name": "DB calf raise",
            "setsReps": "3 × 20",
            "dumbbells": 1
          },
          {
            "slug": "db-shrug",
            "name": "DB shrug",
            "setsReps": "3 × 15",
            "dumbbells": 2
          }
        ]
      },
      {
        "id": "p3-b",
        "badge": "Workout B",
        "name": "Push — heavy sets",
        "exercises": [
          {
            "slug": "db-sumo-squat",
            "name": "DB sumo squat",
            "setsReps": "3 × 12",
            "dumbbells": 1
          },
          {
            "slug": "db-glute-bridge",
            "name": "DB single-leg glute bridge",
            "setsReps": "3 × 15",
            "dumbbells": 1
          },
          {
            "slug": "db-floor-press",
            "name": "DB floor press",
            "setsReps": "3 × 10–12",
            "dumbbells": 2
          },
          {
            "slug": "db-overhead-press",
            "name": "DB overhead press",
            "setsReps": "3 × 10–12",
            "dumbbells": 2
          },
          {
            "slug": "db-lateral-raise",
            "name": "DB lateral raise",
            "setsReps": "3 × 15",
            "dumbbells": 2
          },
          {
            "slug": "db-rear-delt-fly",
            "name": "DB rear delt fly",
            "setsReps": "3 × 12",
            "dumbbells": 2
          },
          {
            "slug": "tricep-kickback",
            "name": "Tricep kickback",
            "setsReps": "3 × 12",
            "dumbbells": 2
          }
        ]
      },
      {
        "id": "p3-c",
        "badge": "Workout C",
        "name": "Pull — heavy sets",
        "exercises": [
          {
            "slug": "db-bulgarian-split-squat",
            "name": "DB Bulgarian split squat",
            "setsReps": "3 × 10 each",
            "dumbbells": 2
          },
          {
            "slug": "db-sumo-squat",
            "name": "DB sumo squat",
            "setsReps": "3 × 12",
            "dumbbells": 1
          },
          {
            "slug": "db-bent-over-row",
            "name": "DB bent-over row",
            "setsReps": "3 × 10–12",
            "dumbbells": 2
          },
          {
            "slug": "db-single-arm-row",
            "name": "DB single-arm row",
            "setsReps": "3 × 10 each",
            "dumbbells": 2
          },
          {
            "slug": "db-shrug",
            "name": "DB shrug",
            "setsReps": "3 × 15",
            "dumbbells": 2
          },
          {
            "slug": "db-face-pull-floor",
            "name": "DB face pull (floor)",
            "setsReps": "3 × 15",
            "dumbbells": 2
          },
          {
            "slug": "hammer-curl",
            "name": "Hammer curl",
            "setsReps": "3 × 12",
            "dumbbells": 2
          }
        ]
      }
    ],
    "coreLabel": "Core — add as a finisher after the main workout. Superset core pairs for efficiency.",
    "core": [
      {
        "name": "DB Russian twist",
        "desc": "Feet raised off floor. Heavier dumbbell. Rotate fully each side.",
        "setsReps": "3 × 15 each side"
      },
      {
        "name": "Hollow body hold",
        "desc": "Lie flat, arms overhead, lower back on floor. Raise shoulders and legs slightly. Hold.",
        "setsReps": "3 × 25–30 sec"
      },
      {
        "name": "DB suitcase carry",
        "desc": "One dumbbell at your side. Walk 15 steps keeping shoulders level. Core fights to stay upright.",
        "setsReps": "3 × 15 steps each side"
      },
      {
        "name": "DB woodchop",
        "desc": "Both hands on one dumbbell. Chop diagonally high to low. Rotation comes from core.",
        "setsReps": "3 × 10 each side"
      },
      {
        "name": "V-up",
        "desc": "Lie flat, raise arms and legs simultaneously to form a V. Lower slowly.",
        "setsReps": "3 × 10"
      },
      {
        "name": "Seated knee tuck (weighted)",
        "desc": "Feet off floor. Hold dumbbell between knees. Draw knees to chest, extend.",
        "setsReps": "3 × 15"
      }
    ]
  },
  {
    "index": 3,
    "tabName": "Mastery",
    "monthsLabel": "Months 10–12",
    "title": "Mastery",
    "goal": "Strict tempo on every rep — 3 seconds lowering, 1-second pause, controlled lift. Same exercises as Phase 3 but the slower lowering phase makes lighter weights feel heavy and dramatically increases time under tension. Sessions run 70–85 min. Take a deload week (50% weight, 2 sets) every 6 weeks.",
    "stats": [
      {
        "label": "Session length",
        "value": "70–75 min"
      },
      {
        "label": "Rest between sets",
        "value": "2 min"
      },
      {
        "label": "Rest between exercises",
        "value": "2 min"
      },
      {
        "label": "Tempo",
        "value": "3s down · 1s pause · lift"
      },
      {
        "label": "Workouts / week",
        "value": "3"
      }
    ],
    "sessionStructure": [
      {
        "time": "5–8 min",
        "desc": "Warm-up — include hip flexor stretch, shoulder circles, thoracic rotation"
      },
      {
        "time": "60–65 min",
        "desc": "Main workout — 7 exercises, 3 sets with strict tempo"
      },
      {
        "time": "5 min",
        "desc": "Cool-down — hold each stretch 30–45 sec"
      }
    ],
    "workoutsLabel": "Workouts — A → B → C rotation, strict tempo",
    "rotationNote": "Tempo: 3 sec lowering · 1 sec pause at bottom · lift normally",
    "workouts": [
      {
        "id": "p4-a",
        "badge": "Workout A",
        "name": "Legs + core — tempo",
        "exercises": [
          {
            "slug": "db-bulgarian-split-squat",
            "name": "DB Bulgarian split squat (tempo)",
            "setsReps": "3 × 10 each",
            "dumbbells": 2
          },
          {
            "slug": "db-sumo-deadlift",
            "name": "DB sumo deadlift (tempo)",
            "setsReps": "3 × 10–12",
            "dumbbells": 2
          },
          {
            "slug": "db-glute-bridge",
            "name": "DB single-leg glute bridge (tempo)",
            "setsReps": "3 × 12",
            "dumbbells": 1
          },
          {
            "slug": "db-step-up",
            "name": "DB step-up (onto step)",
            "setsReps": "3 × 12 each",
            "dumbbells": 2
          },
          {
            "slug": "db-calf-raise-single-leg",
            "name": "DB calf raise — single leg",
            "setsReps": "3 × 15 each",
            "dumbbells": 2
          },
          {
            "slug": "db-shrug",
            "name": "DB shrug (tempo)",
            "setsReps": "3 × 15",
            "dumbbells": 2
          },
          {
            "slug": "renegade-row",
            "name": "Renegade row",
            "setsReps": "3 × 8 each",
            "dumbbells": 2
          }
        ]
      },
      {
        "id": "p4-b",
        "badge": "Workout B",
        "name": "Push — tempo + volume",
        "exercises": [
          {
            "slug": "db-step-up",
            "name": "DB step-up (onto step)",
            "setsReps": "3 × 12 each",
            "dumbbells": 2
          },
          {
            "slug": "db-glute-bridge",
            "name": "DB single-leg glute bridge (tempo)",
            "setsReps": "3 × 15",
            "dumbbells": 1
          },
          {
            "slug": "db-floor-press",
            "name": "DB floor press (tempo)",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-overhead-press",
            "name": "DB overhead press (tempo)",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-rear-delt-fly",
            "name": "DB rear delt fly",
            "setsReps": "3 × 12",
            "dumbbells": 2
          },
          {
            "slug": "db-lateral-raise",
            "name": "DB lateral raise (tempo)",
            "setsReps": "3 × 15",
            "dumbbells": 2
          },
          {
            "slug": "db-tricep-overhead-extension",
            "name": "DB tricep overhead extension (tempo)",
            "setsReps": "3 × 12",
            "dumbbells": 1
          }
        ]
      },
      {
        "id": "p4-c",
        "badge": "Workout C",
        "name": "Pull — tempo + volume",
        "exercises": [
          {
            "slug": "db-bulgarian-split-squat",
            "name": "DB Bulgarian split squat (tempo)",
            "setsReps": "3 × 10 each",
            "dumbbells": 2
          },
          {
            "slug": "db-romanian-deadlift",
            "name": "DB Romanian deadlift (tempo)",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-bent-over-row",
            "name": "DB bent-over row (tempo)",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "single-arm-row-tempo",
            "name": "Single-arm row (tempo)",
            "setsReps": "3 × 10 each",
            "dumbbells": 2
          },
          {
            "slug": "db-shrug",
            "name": "DB shrug (tempo)",
            "setsReps": "3 × 15",
            "dumbbells": 2
          },
          {
            "slug": "db-curl",
            "name": "DB curl (tempo)",
            "setsReps": "3 × 10",
            "dumbbells": 2
          },
          {
            "slug": "db-face-pull-floor",
            "name": "DB face pull (floor)",
            "setsReps": "3 × 15",
            "dumbbells": 2
          }
        ]
      }
    ],
    "coreLabel": "Core — tempo applies here too. Every movement slow and deliberate.",
    "core": [
      {
        "name": "DB ab rollout (floor)",
        "desc": "Kneel, roll dumbbell out slowly as body extends. Pull back before hips touch floor.",
        "setsReps": "3 × 8"
      },
      {
        "name": "Hollow body hold",
        "desc": "30 seconds minimum. Arms overhead, shoulders and legs raised, lower back on floor.",
        "setsReps": "3 × 30–40 sec"
      },
      {
        "name": "DB woodchop (heavy)",
        "desc": "Heavier dumbbell. Controlled rotation high-to-low and low-to-high each side.",
        "setsReps": "3 × 12 each side"
      },
      {
        "name": "DB suitcase carry",
        "desc": "Heavier than Phase 3. Walk slow, shoulders level, core braced the whole time.",
        "setsReps": "3 × 20 steps each side"
      },
      {
        "name": "DB windmill",
        "desc": "One dumbbell overhead, feet wide. Hinge sideways, reach other hand to floor. Eyes on the weight.",
        "setsReps": "3 × 8 each side"
      },
      {
        "name": "V-up with DB pass",
        "desc": "V-up while passing a dumbbell from hands to feet and back. Coordination + full core.",
        "setsReps": "3 × 10"
      }
    ]
  }
];
